# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build 
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.68.3'  

    - name: Build with Hugo
      run: hugo --minify

    - name: Add ssh key
      run: echo ${{ secrets.DEPLOY_KEY }}

    - name: rsync deployments   
      uses: masutech16/rsync-deployments@v1
      with:
        USER_AND_HOST: user@example.com
        DEST: /srv/blog/
        SRC: public/
        RSYNC_OPTIONS: -avzr --delete --exclude node_modules --exclude '.git*'
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        
